// const types = {
//     ADD_TO_CART: 'ADD_TO_CART',
//     CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
//     CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
//     CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
//     RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
// };

// export default types;

export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
